stratagems = [
    ["Machine Gun", "v<v^>", "blue"],
    ["Anti-Material Rifle", "v<>^v", "blue"],
    ["Stalwart", "v<v^^<", "blue"],
    ["Expendable Anti-Tank", "vv<^>", "blue"],
    ["Recoilless Rifle", "v<>><", "blue"],
    ["Flamethrower", "v<^v^", "blue"],
    ["Autocannon", "v><vv^^>", "blue"],
    ["Railgun", "v><vv^<v", "blue"],
    ["Spear", "vv^vv", "blue"],
    ["Jump Pack", "v^^v^", "blue"],
    ["Supply Pack", "^v>v<vv", "blue"],
    ["Grenade Launcher", "^v>v<vvv", "blue"],
    ["Guard Dog Rover", "^v>v<vvv", "blue"],
    ["Ballistic Shield Backpack", "^v><><", "blue"],
    ["Shield Generator Pack", "^v>v<^>>", "blue"],
    ["Guard Dog", "^v>v^>vv", "blue"],
    ["HMG Emplacement", "v^><>><", "green"],
    ["Shield Generator Relay", "^v><>v", "green"],
    ["Tesla Tower", "^v>^v>", "green"],
    ["Anti-Personnel Minefield", "^v>v<^>", "green"],
    ["Laser Cannon", "^v>v<vv", "green"],
    ["Incendiary Mines", "^v><v", "green"],
    ["Arc Thrower", "^><v^v", "green"],
    ["Machine Gun Sentry", "^v>v>>^", "green"],
    ["Gatling Sentry", "^v>v<vv", "green"],
    ["Mortar Sentry", "^v>v>>", "green"],
    ["Autocannon Sentry", "^v>v>v<^", "green"],
    ["Rocket Sentry", "^v>v>>^", "green"],
    ["EMS Mortar Sentry", "^^^vv<", "green"],
    ["Gatling Barrage", ">v<^^", "red"],
    ["Airburst Strike", ">>>", "red"],
    ["120MM HE Barrage", ">vv<v>vv", "red"],
    ["380MM HE Barrage", ">vv^^<vvv", "red"],
    ["Walking Barrage", ">v>v>v", "red"],
    ["Laser Strike", ">^<^><", "red"],
    ["Railcannon Strike", ">v^v<", "red"],
    ["Eagle Strafing Run", "^>>", "red"],
    ["Eagle Airstrike", "^>v>", "red"],
    ["Eagle Cluster Bomb", "^>vv>v", "red"],
    ["Eagle Napalm Airstrike", "^>v^", "red"],
    ["Eagle Smoke Strike", "^>^v", "red"],
    ["Eagle 110MM Rocket Pods", "^v^<", "red"],
    ["Eagle 500KG Bomb", "^<vvv", "red"],
    ["Orbital Precision Strikes", ">>>", "red"],
    ["Orbital Gas Strike", ">>>", "red"],
    ["Orbital EMS Strike", ">>v", "red"],
    ["Orbital Smoke Strike", ">>>", "red"],
    ["Hellbomb", "^v>v^>v>v", "red"],
    ["Reinforce", "v^>v^>", "yellow"],
    ["SOS Beacon", "v^>v^", "yellow"],
    ["Super Earth Flag", "^v^v^", "yellow"],
    ["Upload Data", "<>>^^^", "yellow"]
]
