stratagems = [
      ["LIFT-850 Jump Pack", "v^^v^", "blue"],
      ["B-1 Supply Pack", "v<v^^<", "blue"],
      ["SH-20 Ballistic Shield Backpack", "v<vv^<", "blue"],
      ["SH-51 Directional Shield Backpack", "v^<^>^^", "blue"],
      ["SH-32 Shield Generator Pack", "v^<><>", "blue"],
      ["AX/AR-23 Guard Dog", "v^<^>v", "blue"],
      ["AX/LAS-5 Guard Dog Rover", "v^<^>>", "blue"],
      ["AX/TX-13 Guard Dog Dog Breath", "v^<^>^", "blue"],

      ["MG-43 Machine Gun", "v<>^>", "blue"],
      ["APW-1 Anti-Materiel Rifle", "v<>^v", "blue"],
      ["M-105 Stalwart", "v<^^^<", "blue"],
      ["EAT-17 Expendable Anti-tank", "vv^>", "blue"],
      ["MLS-4X Commando", "v<^>v", "blue"],
      ["GR-8 Recoilless Rifle", "v<>><", "blue"],
      ["FLAM-40 Flamethrower", "v<^v^", "blue"],
      ["AC-8 Autocannon", "v<^^^>", "blue"],
      ["MG-206 Heavy Machine Gun", "v<^vv", "blue"],
      ["RS-422 Railgun", "v>v^<>", "blue"],
      ["FAF-14 Spear Launcher", "vv^vv", "blue"],
      ["GL-21 Grenade Launcher", "v<^<v", "blue"],
      ["LAS-98 Laser Cannon", "v<^<", "blue"],
      ["ARC-3 Arc Thrower", "v>v^<<", "blue"],
      ["LAS-99 Quasar Cannon", "vv^<>", "blue"],
      ["RL-77 Airburst Rocket Launcher", "v^^<>", "blue"],

      ["EXO-45 Patriot Exosuit", "<v>^<vvv", "blue"],
      ["EXO-49 Emancipator Exosuit", "<v>^<vv^", "blue"],

      ["Reinforce", "^v><^", "yellow"],
      ["SOS Beacon", "^v>^", "yellow"],
      ["Resupply", "vv^>", "yellow"],
      ["NUX-223 Hellbomb", "v^<v^>v^", "yellow"],
      ["SSSD Delivery", "vvv^^", "yellow"],
      ["Seismic Probe", "^^<>vv", "yellow"],
      ["Upload Data", "<>^^^", "yellow"],
      ["Eagle Rearm", "^^<^>", "yellow"],
      ["SEAF Artillery", ">^^v", "yellow"],
      ["Super Earth Flag", "v^v^", "yellow"],

      ["E/MG-101 HMG Emplacement", "v^<^>><", "green"],
      ["FX-12 Shield Generator Relay", "vv<><>", "green"],
      ["A/ARC-3 Tesla Tower", "v^>^<>", "green"],
      ["MD-6 Anti-Personnel Minefield", "v<^>", "green"],
      ["MD-I4 Incendiary Mines", "v<<v", "green"],
      ["MD-17 Anti-Tank Mines", "v<^^", "green"],
      ["A/MG-43 Machine Gun Sentry", "v^>^>^", "green"],
      ["A/G-16 Gatling Sentry", "v^>^<", "green"],
      ["A/M-12 Mortar Sentry", "v^>^>v", "green"],
      ["A/AC-8 Autocannon Sentry", "v^>^<^", "green"],
      ["A/MLS-4X Rocket Sentry", "v^>^><", "green"],
      ["A/M-23 EMS Mortar Sentry", "v^>v>", "green"],

      ["Orbital Gatling Barrage", ">v<^^", "red"],
      ["Orbital Airburst Strike", ">>>", "red"],
      ["Orbital 120MM HE Barrage", ">>>3v<>v", "red"],
      ["Orbital 380MM HE Barrage", ">v^^<vv", "red"],
      ["Orbital Walking Barrage", ">v>v>v", "red"],
      ["Orbital Laser", ">v^>v", "red"],
      ["Orbital Railcannon Strike", ">^vv>", "red"],
      ["Orbital Precision Strike", ">>^", "red"],
      ["Orbital Gas Strike", ">>v>", "red"],
      ["Orbital EMS Strike", ">><>v", "red"],
      ["Orbital Smoke Strike", ">>v^", "red"],
      ["Orbital Napalm Barrage", ">>v<^>^", "red"],

      ["Eagle Strafing Run", "^>>", "red"],
      ["Eagle Airstrike", "^>v>", "red"],
      ["Eagle Cluster Bomb", "^>vv>", "red"],
      ["Eagle Napalm Airstrike", "^>v^", "red"],
      ["Eagle Smoke Strike", "^>^v", "red"],
      ["Eagle 110MM Rocket Pods", "^>^<", "red"],
      ["Eagle 500kg Bomb", "^>vvv", "red"]
]
